name: 'Set status check'
inputs:
  outcome:
    description: 'Step outcome'
    required: true
  success-desc:
    reqiured: false
    default: 'Build finished successfully'
  failure-desc:
    reqiured: false
    default: 'Build failed'
  cancelled-desc:
    reqiured: false
    default: 'Build cancelled'
  check-name:
    required: true
  job-id:
    required: true
  step-id:
    required: true
  token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set check status
      uses: Sibz/github-status-action@v1
      with: 
        authToken: ${{inputs.token}}
        context: ${{ inputs.check-name }}
        description: ${{ inputs.outcome == 'failure' ? inputs.failure-desc : (inputs.outcome == 'success' ? inputs.success-desc : inputs.cancelled-desc) }}
        state: ${{ inputs.outcome }}
        sha: ${{github.event.pull_request.head.sha || github.sha}}
        target_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/job/${{inputs.job-id }}#step:${{ inputs.step-id }}
