name: Fix builds
run-name: Fix ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
        version:
            type: string
            required: true
        ref:
            type: string
            required: true

jobs:
    fix:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                fetch-tags: true
                ref: ${{ inputs.ref }}
            - name: Setup JDK 17
              uses: actions/setup-java@v2
              with:
                  java-version: '17'
                  distribution: 'temurin'
        
            - name: Setup with Gradle
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: :neoforge:setup
                  cache-read-only: false
            
            - name: Build installer
              uses: gradle/gradle-build-action@v2
              with:
                  arguments: :neoforge:signInstallerJar
                  cache-read-only: false
            
            - uses: fjogeleit/http-request-action@v1
              with:
                url: https://maven.neoforged.net/releases/net/neoforged/neoforge/${{ inputs.version }}/neoforge-${{ inputs.version }}-installer.jar
                method: 'POST'
                username: ${{ secrets.USER }}
                password: ${{ secrets.PASS }}
                file: ${{ github.workspace }}/projects/neoforge/build/libs/neoforge-${{ inputs.version }}-installer.jar